version: '2.4'

volumes:
  public:
    driver: local

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
  release:
    build:
      context: .
      dockerfile: Dockerfile
    image: 639119023535.dkr.ecr.ap-southeast-1.amazonaws.com/mjcv/todobackend:latest
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings_release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
  app:
    image: 639119023535.dkr.ecr.ap-southeast-1.amazonaws.com/mjcv/todobackend:${APP_VERSION}
    extends:
      service: release
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -fs localhost:8000
      interval: 3s
      retries: 10
    ports:
      - 8000
    volumes:
      - public:/public
    command:
      - uwsgi
      - --http=0.0.0.0:8000
      - --module=todobackend.wsgi
      - --master
      - --check-static=/public
      - --die-on-term
      - --processes=4
      - --threads=2
  migrate:
    extends:
      service: release
    depends_on:
      db:
        condition: service_healthy
    command:
      - python3
      - manage.py
      - migrate
      - --no-input
  db:
      image: mysql:5.7
      healthcheck:
        test: mysqlshow -u $$MYSQL_USER -p$$MYSQL_PASSWORD
        interval: 3s
        retries: 10
      environment:
        MYSQL_DATABASE: todobackend
        MYSQL_USER: todo
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
